### PR TITLE
Improve image build

### PR DESCRIPTION
**Pull request by fostermh**
reorganize the dockerfile to hopefully build the ckan docker image in a more efficient way. uses multistage builds which should allow for parallel processing of some steps. Should also improve cache hits and thus make development builds faster

### CODE REVIEW

**Comment by fostermh** [comment]
enabled caching in github action docker build. cut the build time in half.

**Comment by fostermh** [comment]
@ogsletcax I would love to get your feedback on this. still room for improvement but I'm tired of fiddling with dockerfiles for now.

**Comment by ogsletcax** [comment]
@fostermh I'm trying to checkout this branch with `git checkout improve_ckan_build_time` or `git checkout origin/improve_ckan_build_time`. 

but it doesn't work. I can't see it in sourcetree either.. any idea?

**Comment by fostermh** [comment]
sorry, the branch is called 'improve_ckan_build_time_and_size'

**Review by ogsletcax — APPROVED** [review]

**Comment by ogsletcax** [comment]
@fostermh The build is much faster! I not sure the multistage build is super useful is this case but it works fine! Thx!

**Comment by fostermh** [comment]
great! glad it works for you as well. My thinking around using the multistage build is that if an extension is updated only that stage has to be rebuilt and everything else can come from the cache. I will have to work with it for a while to see if that is true.
We could put every extension in its own stage but I was tired of typing. The other advantage of multistage builds is the option to use parallel processing though my version of docker-compose is too old to take advantage of that currently.

**Pull request merged**
