### PR TITLE
Add citation field to dataset

### LINKED ISSUE #30: Add citation to dataset page
Adding a citation example to each dataset page has been discussed for a while.

**Solution:**
Initially, a hard-coded citation in any format would be sufficient. Ultimately it would be nice to be able to provide users with citations in the format they want. 

**Describe alternatives you've considered**

**Additional context**

- Citation example string
  - Esip: https://esip.figshare.com/articles/Data_Citation_Guidelines_for_Earth_Science_Data_Version_2/8441816
- Refworks/RIS file export Export a RIS file (example formats below)
  - https://www.jstor.org/stable/26897827

Python options:
- https://github.com/MrTango/rispy
- https://pypi.org/project/cffconvert/

JS options:
- https://citation.js.org/ and https://github.com/citation-js/replacer

### PR DESCRIPTION
**Pull request by fostermh**
add a citation field to dataset dictinary
add citation output to dataset page which allows the download and display of citations in mutiple fomrats.
add citation to solr index

Fix #30
Depends on cioos-siooc/ckanext-cioos_theme#37
Depends on cioos-siooc/cioos-siooc-schema#10
Depends on cioos-siooc/ckanext-spatial#15
Depends on cioos-siooc/ckanext-cioos_harvest#9

### CODE REVIEW

**Comment by sjbruce** [comment]
Tested PR59 and I can update and download citations from DOI and Wikidata so far.

The `authorTitleYear `option seems to only return `[object Object]` which looks like a JS issue - possibly the library not delving far enough into the objects to extract their content.

**Comment by fostermh** [comment]
I will resolve conflicts soon so we can better test

**Comment by fostermh** [comment]
submodules have been updated. the conflicts are due to submodules being on a branch rather than master. once this pr is approved I will merge the marches back to master and update the CKAN repo to reflect the changes

**Comment by fostermh** [comment]
Some fairly heavy changes to this pull request. Citations should now populate from the xml during harvest. This can be overwritten later by manually editing or ckan api calls if needed. The citation field will now accept all of the downloadable outputs as input with the exception of autherTitleYear which is just silly. You can test this by editing the field through the ckan dataset editor.

@sjbruce and @ogsletcax if you could review when you have time to see if this meets your needs it would be most helpful

You should be able to follow the instructions [higher up](https://github.com/cioos-siooc/ckan/pull/59#issuecomment-785319023) to pull the relevant ckan PR image. This image should have all the relevant submodule branches baked into it as well. Let me know if running this image doesn't work for you.

**Comment by ogsletcax** [comment]
@fostermh the fields citation and harvest_document_content are added to sorl schema, does it make these fields mandatory?

**Review by ogsletcax — APPROVED** [review]

**Pull request merged**
